id: I134B804D
legacy_id: P003191
ocr_import_info:
  bdrc_scan_id: W00KG01622
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T07:38:12'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-29T11:33:14.755952+00:00'
last_modified: 2022-08-29 19:33:27.497695
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00KG01622
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW00KG01622
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྗེ་གྲུབ་ཐོབ་ཆེན་པོ་དགེ་སློང་པདྨ་དཀར་པོར་སྐྱེ་བ་བཞེས་པའི་ཚེ་འཕགས་པ་སྤྱན་རས་གཟིགས་ལ་གསོལ་བ་བཏབ་པའི་རྡོ་རྗེའི་གསུང་།
  author: གྲུབ་ཆེན་ཐང་སྟོང་རྒྱལ་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.7063378573299998
  ocr_word_median_confidence_index: 0.8799999952316284
quality: null
bases:
  I00KG02882:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG02882
      total_pages: 6
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00KG02882.txt
    statistics:
      ocr_word_median_confidence_index: 0.8799999952316284
      ocr_word_mean_confidence_index: 0.7063378573299998
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
