id: I134B804D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T07:38:18+00:00'
last_modified: '2022-06-07T18:18:26.249303+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG01622
  title: རྗེ་གྲུབ་ཐོབ་ཆེན་པོ་དགེ་སློང་པདྨ་དཀར་པོར་སྐྱེ་བ་བཞེས་པའི་ཚེ་འཕགས་པ་སྤྱན་རས་གཟིགས་ལ་གསོལ་བ་བཏབ་པའི་རྡོ་རྗེའི་གསུང
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    146F:
      image_group_id: I00KG02882
      title: ''
      total_pages: 6
      order: 1
      base_file: 146F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
