id: opecha:P003191
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG01622
  title: རྗེ་གྲུབ་ཐོབ་ཆེན་པོ་དགེ་སློང་པདྨ་དཀར་པོར་སྐྱེ་བ་བཞེས་པའི་ཚེ་འཕགས་པ་སྤྱན་རས་གཟིགས་ལ་གསོལ་བ་བཏབ་པའི་རྡོ་རྗེའི་གསུང
  volume: ''
  author: ''
